# Generated by Django 4.0.1 on 2022-01-23 17:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoviePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('movie_name', models.TextField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MovieToTrailers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailers', models.TextField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
            ],
        ),
        migrations.CreateModel(
            name='MovieToPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.platform')),
            ],
        ),
        migrations.CreateModel(
            name='MovieToPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
            ],
        ),
        migrations.CreateModel(
            name='MovieToLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.language')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
            ],
        ),
        migrations.CreateModel(
            name='MovieToLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
            ],
        ),
        migrations.CreateModel(
            name='MovieToGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.genre')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
            ],
        ),
        migrations.CreateModel(
            name='MovieToCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.certificate')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
            ],
        ),
        migrations.CreateModel(
            name='MovieToAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.awards')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
            ],
        ),
        migrations.CreateModel(
            name='MoviePostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('neutral', models.IntegerField()),
                ('ebits_rating', models.FloatField()),
                ('ebits_review', models.TextField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
            ],
        ),
        migrations.CreateModel(
            name='CriticReviewDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.TextField()),
                ('review_author', models.TextField()),
                ('review_rating', models.FloatField()),
                ('review_title', models.TextField()),
                ('review_date', models.DateField()),
                ('critic_review', models.TextField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
            ],
        ),
        migrations.CreateModel(
            name='CastDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name', models.TextField()),
                ('cast_role', models.TextField()),
                ('cast_image', models.ImageField(upload_to='')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.moviepost')),
            ],
        ),
    ]
