# Generated by Django 4.0.1 on 2022-01-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietogenre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movietoplatform',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.AddField(
            model_name='moviepost',
            name='thumbnail_image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
