# Generated by Django 4.0.1 on 2022-01-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_castdetails_cast_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castdetails',
            name='cast_image',
            field=models.ImageField(default=None, null=True, upload_to='<built-in function id>/upload/'),
        ),
        migrations.AlterField(
            model_name='moviepost',
            name='thumbnail_image',
            field=models.ImageField(default=None, null=True, upload_to='<django.db.models.fields.UUIDField>/upload/'),
        ),
        migrations.AlterField(
            model_name='movietophotos',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='<django.db.models.fields.related.ForeignKey>/upload/'),
        ),
    ]
