# Generated by Django 4.0.2 on 2023-05-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
